version: '3'
services:
  crowi:
    build:
      context: .
      args:
        NODE_ENV: development
    tty: true
    environment:
      DEBUG: 'crowi:*'
      MONGO_URI: mongodb://mongodb:27017/crowi
      REDIS_URL: redis://redis:6379/crowi
      ELASTICSEARCH_URI: elasticsearch:9200/
      PLANTUML_URI: //localhost:8080
      FILE_UPLOAD: conoha
      CONOHA_USER:
      CONOHA_PASS:
      CONOHA_AUTH_URL:
      CONOHA_REGION:
      CONOHA_TENANT_ID:
      CONOHA_CONTAINER:
      CROWI_ADMINS: "temma sappi_red"
      CROWI_INVALIDATE_TOKENS: ""
    volumes:
      - ./:/crowi
      - /crowi/node_modules
    ports:
      - 3000:3000
    links:
      - elasticsearch
      - redis
      - plantuml
    networks:
      - crowi_network

  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      xpack.graph.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.security.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - crowi_network

  redis:
    image: redis:4.0.8
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - crowi_network

  plantuml:
    image: plantuml/plantuml-server:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - crowi_network

networks:
  crowi_network:
    external: true
