version: '3'
services:
  crowi:
    build:
      context: .
      args:
        NODE_ENV: development
    tty: true
    environment:
      DEBUG: "crowi:*"
      MONGO_URI: mongodb://mongodb:27017/crowi
      REDIS_URL: redis://redis:6379/crowi
      ELASTICSEARCH_URI: elasticsearch:9200
      PLANTUML_URI: //localhost:8080
      FILE_UPLOAD: local
      CROWI_ADMINS: "temma sappi_red hijiki51 yukikurage"
      CROWI_INVALIDATE_TOKENS: ""
    volumes:
      - ./:/crowi
      - /crowi/node_modules
    ports:
      - 3000:3000
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy
    links:
      - mongodb
      - elasticsearch
      - redis
      - plantuml
    command: bash -c "npm install && npm run dev"

  mongodb:
    image: mongo:3.6.3
    volumes:
      - mongodb:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017

  elasticsearch:
    image: "ghcr.io/traptitech/es-with-sudachi-crowi:6.8.9-2.1.0"
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    # healthcheck:
    #   test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/lib/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    image: redis:4.0.8
    restart: unless-stopped
    ports:
      - 6379:6379

  plantuml:
    image: plantuml/plantuml-server:latest
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mongodb:
